### PR TITLE
Adds Gateway!

### PR DESCRIPTION
**Pull request by itsjoekent**

### CODE REVIEW

**Review by DFurnes — COMMENTED** [review]
Tiny StyleCI nitpick, but otherwise looks good!

**Comment by itsjoekent** [comment]
@DFurnes Wercker build failing 

```
FFFPHP Fatal error:  Call to undefined method Symfony\Component\HttpFoundation\Response::getTargetUrl() in /pipeline/build/vendor/laravel/framework/src/Illuminate/Foundation/Testing/InteractsWithPages.php on line 109
PHP Fatal error:  Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable.' in /pipeline/build/bootstrap/cache/compiled.php:1294
Stack trace:
#0 /pipeline/build/bootstrap/cache/compiled.php(1242): Illuminate\Container\Container->build('Illuminate\Cont...', Array)
#1 /pipeline/build/bootstrap/cache/compiled.php(1783): Illuminate\Container\Container->make('Illuminate\Cont...', Array)
#2 /pipeline/build/bootstrap/cache/compiled.php(2102): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#3 /pipeline/build/bootstrap/cache/compiled.php(2071): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#4 /pipeline/build/bootstrap/cache/compiled.php(2089): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#5 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#6 {main}
  thrown in /pipeline/build/bootstrap/cache/compiled.php on line 1294
```

Not really sure what thats about, doesn't seem related to my PR?

**Comment by DFurnes** [comment]
Oh, I think it's because we didn't update [the mocks](https://github.com/DoSomething/voting-app/blob/09bd6cf564c22eca021ed194d5ac58594049b700/tests/VotingTest.php#L30) to use the new Gateway Northstar client:

``` diff
- $northstarMock = $this->mock(\DoSomething\Northstar\NorthstarClient::class);
+ $northstarMock = $this->mock(\DoSomething\Gateway\Northstar::class);
```

**Comment by itsjoekent** [comment]
Ohh

**Comment by itsjoekent** [comment]
Strange, It seems I replaced all of the mocks but same error

**Comment by itsjoekent** [comment]
Actually let me check, I think its because of this old NorthstarUser reference

**Comment by itsjoekent** [comment]
nope, still something else wrong

**Comment by itsjoekent** [comment]
Thanks @DFurnes!

**Comment by DFurnes** [comment]
Woo! 🎉

Give a quick look over the changes, and if all looks good we can merge :)

**Comment by itsjoekent** [comment]
Looks good to me!

**Pull request merged**
