### PR TITLE
Revert webpack

### PR DESCRIPTION
**Pull request by pnasrat**
This set of commits reverts my attempt to migrate to webpack. Tested wercker using `wercker local`

### CODE REVIEW

**Comment by pnasrat** [comment]
`Your distribution, identified as "trusty", is not currently supported,`

**Comment by pnasrat** [comment]
Hmm https://deb.nodesource.com/node_6.x/dists/trusty/Release

**Comment by pnasrat** [comment]
```
curl -sLf -o /dev/null 'https://deb.nodesource.com/node_6.x/dists/trusty/Release' && echo supported
supported
```

**Comment by pnasrat** [comment]
image

**Review by DFurnes — APPROVED** [review]

**Comment by pnasrat** [comment]
weird

```
*** [err :: catsgg] find:
*** [err :: catsgg] `/var/www/catsgg/releases/20170608151734/public/images'
*** [err :: catsgg] : No such file or directory
*** [err :: catsgg] 
*** [err :: catsgg] find:
*** [err :: catsgg] `/var/www/catsgg/releases/20170608151734/public/stylesheets'
*** [err :: catsgg] : No such file or directory
*** [err :: catsgg] 
*** [err :: catsgg] find:
*** [err :: catsgg] `/var/www/catsgg/releases/20170608151734/public/javascripts'
*** [err :: catsgg] : No such file or directory
*** [err :: catsgg] 
    command finishe
```

**Pull request merged**
