### PR TITLE
Fix static assets and CSS

### PR DESCRIPTION
**Pull request by pnasrat**
Use webpack 1.1 consistent with older projects.
Use copy-webpack-plugin for static assets

### CODE REVIEW

**Comment by pnasrat** [comment]
``` diff -u /tmp/assets1.txt /tmp/new-assets.txt
--- /tmp/assets1.txt	2017-06-06 13:12:35.000000000 -0400
+++ /tmp/new-assets.txt	2017-06-06 16:30:02.000000000 -0400
@@ -1,6 +1,5 @@
-/Users/pnasrat/Sites/voting-app/public/assets/
-├── app-35fb45a19bed15ab28cc.js
-├── app-35fb45a19bed15ab28cc.js.map
+/Users/pnasrat/Sites/voting-app/public/assets
+├── app.js
 ├── fonts
 │   ├── icomoon
 │   │   ├── icomoon.eot
@@ -21,9 +20,8 @@
 │   ├── search_fallback.png
 │   ├── touch_icon.default.png
 │   └── twitter_share.default.jpg
-├── rev-manifest.json
 └── vendor
     ├── html5shiv.min.js
     └── respond.min.js

-5 directories, 21 files
+5 directories, 19 files
```

**Comment by pnasrat** [comment]
comparing Dec 1 file build tree with this - I need to readd the hashing type thing somehow but this is better.

**Comment by pnasrat** [comment]
screen shot 2017-06-06 at 16 35 58

**Comment by DFurnes** [comment]
Why did we switch back to Webpack 1.1 here?

**Comment by pnasrat** [comment]
I was having weird interactions when I was trying to get stuff to work I wanted a working site so we can deploy safely and then figure upgrades - I got sucked into should I move to laravel 5.4 and mix vs elixir and so on and very confused so I looked at what one of the other projects - northstar I think and that was 1.x and was easiest to get workign

**Comment by DFurnes** [comment]
Okay, no problem! Webpack stuff can get pretty hairy. Let me know if you want to look into it together sometime, otherwise I'll make an issue and we can revisit whenever we next launch a voting campaign.

**Review by DFurnes — APPROVED** [review]

**Comment by pnasrat** [comment]
Had to fix `DEPLOY_PATH` and add the wercker ssh key to `jump`

**Pull request merged**
