### PR TITLE
Categories of winners

### PR DESCRIPTION
**Pull request by DFurnes**
#### Changes

Adds multiple categories for winners in Voting App! This allows us to have distinct “winner” categories like “Top 20” that don’t map to candidate categories like “Basketball”.

:trophy: 
#### How should this be manually tested?

Seed the database, make some winner categories, then make some winners. I'd like to add some automated tests for this when I get the chance.
#### Screenshots

screen shot 2015-11-18 at 3 54 33 pm

---

For review: @angaither @weerd

### CODE REVIEW

**Comment by angaither** [comment]
:+1:

**Comment by angaither** [comment]
wowowow :+1:

**Comment by DFurnes** [comment]
:bow:

**Comment by weerd** [comment]
@_@ :dancer:

**Pull request merged**
