### PR TITLE
database migration to remove writein_link setting

### PR DESCRIPTION
**Pull request by katiecrane**
as per [this discussion](https://github.com/DoSomething/voting-app/issues/505#issuecomment-209989593)

image

cc: @namimody

### CODE REVIEW

**Comment by DFurnes** [comment]
screen shot 2016-04-14 at 11 21 06 am

:+1:

**Comment by namimody** [comment]
@katiecrane sorry to clarify -- because the write_ins field using Markdown, we don't need the old additional field?

**Comment by katiecrane** [comment]
@namimody Yeah we changed it so that the entire write in text is customizable now. Before, it was pre-written text that pulled in the candidate type and the write-in link, but that doesn't exist anymore and was the only thing that used the write-in link, so we 🔥 'd it.

**Comment by namimody** [comment]
:fire: :hushed:

**Pull request merged**
