### PR TITLE
allow admins to toggle accepting write ins

### LINKED ISSUE #505: Add ability to remove "write in" text at the bottom of the page.
We want to be able to toggle off the "Was there a candidate we missed?" blurb at the bottom of the page for this campaign. It might make sense to refactor this section to be a Markdown text area (rather than hard-coded copy), and then conditionally display it only if the text area is not empty.

### PR DESCRIPTION
**Pull request by katiecrane**
- admins can now choose whether or not to show write in text
- includes database migration to add new setting
### Issues:

Fixes #505

### CODE REVIEW

**Comment by DFurnes** [comment]
I think it could be a good idea to make this whole text area (everything inside the `<div class="wrapper -narrow">`) an editable Markdown text field, like we do for the tagline in the navigation. Then we could just hide it if the text field is empty, rather than adding another toggle.

**Comment by katiecrane** [comment]
@DFurnes 🍁 ing toggle city!

**Comment by DFurnes** [comment]
:+1:

**Pull request merged**
